// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAed8e79eDecodeTrafficDataProcessingModel(in *jlexer.Lexer, out *Road) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "tti_id":
			out.TtiID = int(in.Int())
		case "tti_name":
			out.TtiName = string(in.String())
		case "wkt_road":
			out.WktRoad = string(in.String())
		case "Roads":
			if in.IsNull() {
				in.Skip()
				out.Roads = nil
			} else {
				in.Delim('[')
				if out.Roads == nil {
					if !in.IsDelim(']') {
						out.Roads = make([]string, 0, 4)
					} else {
						out.Roads = []string{}
					}
				} else {
					out.Roads = (out.Roads)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Roads = append(out.Roads, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAed8e79eEncodeTrafficDataProcessingModel(out *jwriter.Writer, in Road) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"tti_id\":"
		out.RawString(prefix)
		out.Int(int(in.TtiID))
	}
	{
		const prefix string = ",\"tti_name\":"
		out.RawString(prefix)
		out.String(string(in.TtiName))
	}
	{
		const prefix string = ",\"wkt_road\":"
		out.RawString(prefix)
		out.String(string(in.WktRoad))
	}
	{
		const prefix string = ",\"Roads\":"
		out.RawString(prefix)
		if in.Roads == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Roads {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Road) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAed8e79eEncodeTrafficDataProcessingModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Road) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAed8e79eEncodeTrafficDataProcessingModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Road) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAed8e79eDecodeTrafficDataProcessingModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Road) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAed8e79eDecodeTrafficDataProcessingModel(l, v)
}
