// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  model

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Road ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Road ) UnmarshalJSON([]byte) error { return nil }
func ( Road ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Road ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Road *Road
